### ISSUE TITLE
Use of https://github.com/olekukonko/tablewriter to write beautiful table

### ISSUE THREAD

**Issue by matcornic** [jaytaylor/html2text#14]
Hello,

I'm maintainer of [Hermes](https://github.com/matcornic/hermes), a Golang package that generates clean, responsive HTML e-mails for sending transactional mail.

I'm thinking about using your really nice package to help generate plain text email as fallbacks of HTML ones. Everything is working great, but generated tables are not as clean as I would want.

Would you replace its implementation with https://github.com/olekukonko/tablewriter ?

For example, 

1. Given: a [table like this](https://github.com/matcornic/hermes/blob/master/screens/default/receipt.png)

2. Actual result, using current version of html2text :

```
Item Description Price
Golang Open source programming language that makes it easy to build simple, reliable, and efficient software $10.99
Hermes Programmatically create beautiful e-mails using Golang. $1.99
```

3. Expected result, using https://github.com/olekukonko/tablewriter

```
+--------+--------------------------------+--------+
|  ITEM  |          DESCRIPTION           | PRICE  |
+--------+--------------------------------+--------+
| Golang | Open source programming        | $10.99 |
|        | language that makes it easy    |        |
|        | to build simple, reliable, and |        |
|        | efficient software             |        |
| Hermes | Programmatically create        | $1.99  |
|        | beautiful e-mails using Golang |        |
+--------+--------------------------------+--------+
```

Btw, thank you for the great work :)

**Comment by jaytaylor** [comment]
Hey @matcornic!

Thanks for reaching out, your proposed way is much better; infinitely more practical, useful, and beautiful.

Are you able to perform the integration and open a PR?

Otherwise it could be awhile before it surfaces to the top of my TODO list.

Best,
Jay

**Comment by matcornic** [comment]
@jaytaylor Thanks for the quick reply.

I understand, I have mine as well 😆 
I'll try to look into it since it fits _my_ needs and not yours.
