### ISSUE TITLE
link textifying

### ISSUE THREAD

**Issue by firewut** [jaytaylor/html2text#2]
Is it correct behaviour:

    <li>Link 1: <a href="https://example.com">Example.com</a></li>
   
    Link 1:
    https://example.com

Maybe making a
    
    Link 1: Example.com

could be better way ?:D

**Comment by jaytaylor** [comment]
I like your proposed better way.  A PR with corresponding unit-test would
be most welcome :)

**Comment by korya** [comment]
The issue was handled  in https://github.com/jaytaylor/html2text/pull/3. I believe it can be closed.

**Comment by jaytaylor** [comment]
Thanks @korya, closing this out.
