### ISSUE TITLE
Properly trim white space of text nodes

### ISSUE THREAD

**Issue by Kleissner** [jaytaylor/html2text#29]
Line https://github.com/jaytaylor/html2text/blob/master/html2text.go#L340 should use the `strings.TrimSpace` function instead of `strings.Trim` to properly trim white spaces (especially unicode ones).

```go
data = strings.TrimSpace(spacingRe.ReplaceAllString(node.Data, " "))
```

**Comment by jaytaylor** [comment]
Thanks, and sorry about only seeing this now.

I'll gladly accept a PR for this one!

**Comment by mikemccrary** [comment]
I've created PR https://github.com/jaytaylor/html2text/pull/34 for this. Let me know how it looks, thanks!

**Comment by mikemccrary** [comment]
@jaytaylor going to bump this incase it got missed

**Comment by jaytaylor** [comment]
Hi Mike, thanks for the reminder!  Merged it.
