### ISSUE TITLE
jaytaylor.com website is down

### ISSUE THREAD

**Issue by AlaaAttya** [jaytaylor/html2text#31]
jaytaylor.com website is down which makes the package not accessible

**Comment by Kleissner** [comment]
Just use instead:
```go
import "github.com/jaytaylor/html2text"
```

**Comment by jaytaylor** [comment]
Had it fixed shortly thereafter.

**Comment by UtkarshGpta** [comment]
@jaytaylor Updated README to solution suggested by @Kleissner. This way, we won't have to rely on jaytaylor.com domain availability. #60
